### PR TITLE
Search by Company implemented

### PR DESCRIPTION
**Pull request by Nik-git1**
I have implemented a search bar functionality using pure JS. This is my first open-source contribution, open to feedback and guidance.
PS:- after searching for a company, maybe we can use "role" attribute instead of mapped_role to get a better compensation distribution for the company.

### CODE REVIEW

**Comment by kuutsav** [comment]
Thanks for the PR @Nik-git1. I'll try to review it by tomorrow.
Can you add a screenshot as well?

> PS:- after searching for a company, maybe we can use "role" attribute instead of mapped_role to get a better compensation distribution for the company.

This is a good idea but we can't bypass role sanitisation. L62 can be written as l62, 62, L-62, ... for example. Mapped role is supposed to tackle this, otherwise you'll end up with counts being split into multiple roles. We could maintain another mapping for `company -> most_common_company_role -> mapped_role`. Need to think more about this issue though.

**Comment by Nik-git1** [comment]
Sure, 
Screenshot (10)
Screenshot (11)
Haven't made any UI changes for now, we can maybe adjust plot sizes according to number of data points.

**Comment by kuutsav** [comment]
This looks good but let's have the search bar and button just above "#  ID" column in the table. Left end of the div which contains "previous and next" buttons.

> Haven't made any UI changes for now, we can maybe adjust plot sizes according to number of data points.

Don't worry about this point in this PR, let's keep the PRs short and to the point.

**Comment by Nik-git1** [comment]
Done, do let me know if some more changes are required.
Screenshot 2024-06-12 151736

**Comment by kuutsav** [comment]
Looks good, will review it today. Thanks!

**Review by kuutsav — APPROVED** [review]
Thanks again 🚀.

I've made a minor formatting change (made the search bar smaller).

**Pull request merged**
