### PR TITLE
Sorting based on compensation and yoe

### PR DESCRIPTION
**Pull request by Nik-git1**
Implemented in Pure JS
1) To reset sort Page refresh of search(even null) is required, could potentially solve this by adding sort on ID parameter as well.
2) No indicator if sort is available on any header , initially the table looks exactly the same, could add maybe a dot(.) in front of the header name.
Do let me know if any changes are required.

sort 1
sort 2
sort 3

### CODE REVIEW

**Comment by kuutsav** [comment]
Few nits:
- Total/Base column header is aligned right, so please add the sort button to it's left so that it does not move "Total" text.
- Add sorting on "#" as well to allow the user to reset without refresh (technically it doesn't matter as it's static content at users end, but many folks won't know this detail).
- Maybe use this for sorting 🡳, the one in screenshots looks too skinny.

Thanks again for picking this up @Nik-git1

**Comment by Nik-git1** [comment]
Actually, the # column is an index of the table, not the data , so it never gets scrambled, the user might not be able to know whether to click it to remove the sorting intuitively. We may have to logically assign the indexes(or do mapping while loading the data) to each data point first before using this.

**Comment by kuutsav** [comment]
Makes sense. In that case, what about this - first click sorts by descending, 2nd by ascending and 3rd click resets it. This is common behaviour in such designs i presume. The arrow should color tone could be lighter in the reset mode.

**Comment by Nik-git1** [comment]
What about using a dot(.) as default, helps indicate the sorts are available as well?

**Comment by kuutsav** [comment]
Works 👍

**Comment by Nik-git1** [comment]
Completed , found something better for default state 
sort 6

**Pull request merged**
