### PR TITLE
feat:navigate-to-table-on-chart-data-series-click

### PR DESCRIPTION
**Pull request by sonuKumar03**
### Description
This PR adds feature to navigate to table compensation when user clicks on column bar.
this also adds 
1. Pagination info on table 
Screenshot 2024-06-15 at 11 09 08 AM

3. Reset button
Visible when user has applied filters
Screenshot 2024-06-15 at 11 09 42 AM

### Hows it has been tested 
manually

###  Screenshot

https://github.com/kuutsav/leetcode-compensation/assets/45958357/38f8c195-3d60-4bdc-b512-7ddc7fdc3cec

### CODE REVIEW

**Comment by kuutsav** [comment]
@sonuKumar03 I just merged another pagination related PR, can you remove the pagination related changes in your PR and resolve the conflicts? The bar chart click feature is cool. Thanks!

**Comment by sonuKumar03** [comment]
@kuutsav let me do it🫡

**Comment by sonuKumar03** [comment]
UI after changes are rebased.
Screenshot 2024-06-15 at 1 32 52 PM

**Comment by kuutsav** [comment]
@sonuKumar03 Sorry but what i meant was remove all the changes related to pagination. I wan to keep the UI as clutter free as possbile. With the addition of pages in the dropdown, <page_start> - <page_end> is not adding much additional info.
Let's only bring in the dropdown click -> data update in this PR.

**Pull request closed without merging**
